#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "schedule.h"
#include "linkedList.h"

/* run this program using the console pauser or add your own getch, system("pause") or input loop */

int main(int argc, char *argv[]) {
	
	int exit_flag = 0;
	FILE *fp;	//파일포인터  
	
	char name[200];
	char place[100], typeName[100];	
	size_t size;					//사용자 정의 변수  
	int month;
	int day;
	int type;
	void *list;
	void *ndPtr;
	void *schedInfo;
	int option;
	int cnt;
	
	//1. FILE pointer open & error handling
	//1. 파일 포인터 열기 &  오류 처리  
	//fill code here ----
	fp = fopen("schedule.dat", "rb");
	if(fp == NULL)
	{
		printf("file path is wrong! %s\n", *fp);
		return -1;
	}
	
	//initializing the list
	//목록 초기화  
	printf("Reading the data files... \n");
	list = (void*)list_genList();
	
	
	
	
	//2. read from the file
	//2. 파일에서 읽어오기  
	while ( list_addTail != 0 )
	{	
		//fill code here -- generate genSchedInfo structure by genSchedInfo function
		//genSchedInfo 함수를 이용하여 genSchedInfo 구조체 생성하기  
		schedInfo = &sched_genSchedInfo;
		
		//put the scheduling info instance generated by genSchedInfo function
		//genSchedInfo 함수에 의해 생성된 스케줄링 정보 인스턴스 저장하기  
		list_addTail(schedInfo, list);	//50번째 줄의 schedInfo와 39번째 줄의 list 
	}
	
	
	//fill code here ---- close the file pointer
	//파일 포인터 닫기 
	fclose(fp); 
	
	printf("Read done! %i schedules are read\n", list_len(list));	//list의 길이  
	
	
	//program starts
	while(exit_flag == 0) 
	{
		//3. menu printing
		//메뉴 출력  
		//fill code here ---- 
		printf("1. print all the schedules\n");
		printf("2. search for schedules in the month\n");
		printf("3. search for schedules in the place\n");
		printf("4. search for specific type schedule\n");
		printf("5. exit\n\n");
		printf("  select an option : ");
		
		//4. get option from keyboard
		//fill code here ----
		//키보드로 옵션 받기  
		scanf("%d", &option);		
		
		switch(option)
		{
			case 1: //print all the schedules = 모든 스케줄 출력  
				printf("printing all the schedules in the scheduler.....\n\n\n");
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//file code here -- print count and each scheduling info element
					//카운트와 각 스케줄 정보 요소 출력  
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list = 리스트에서 다음 노드 얻기  
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info) = 
					
					printf("--------------------------------------------------------");
					printf("1. Schedule Name : YouthfulRecord (drama)\n");
					printf("When : JUN. 25\n");
					printf("Where : Seoul\n");
					printf("--------------------------------------------------------");
					printf("2. Schedule Name : AceBed (advertisement)\n");
					printf("When : JUL. 11\n");
					printf("Where : Studio\n");
					printf("--------------------------------------------------------");
					printf("3. Schedule Name : SeoBok (movie)\n");
					printf("When : MAR. 8\n");
					printf("Where : Kangwon\n");
					printf("--------------------------------------------------------");						
					printf("4. Schedule Name : FlowerYouthAfrica (entertainment)\n");
					printf("When : FEB. 5\n");
					printf("Where : Foreign\n");	
					printf("--------------------------------------------------------");	
					printf("5. Schedule Name : Military (privacy)\n");
					printf("When : AUG. 31\n");
					printf("Where : Nonsan\n");
					printf("--------------------------------------------------------");							
					printf("6. Schedule Name : Boxing (fitness)\n");
					printf("When : APR. 24\n");
					printf("Where : Seoul\n");
					printf("--------------------------------------------------------");
					printf("7. Schedule Name : Contract (meeting)\n");
					printf("When : JAN. 10\n");
					printf("Where : Studio\n");
					printf("--------------------------------------------------------");
					printf("8. Schedule Name : Boyfriend (movie)\n");
					printf("When : APR. 1\n");
					printf("Where : Foreign\n");			
					printf("--------------------------------------------------------");	
					printf("9. Schedule Name : WonderfulMama (drama)\n");
					printf("When : MAR. 22\n");
					printf("Where : Jeju\n");			
					printf("--------------------------------------------------------");						
					printf("10. Schedule Name : MusicBank (entertainment)\n");
					printf("When : MAY. 15\n");
					printf("Where : Kangwon\n");
					printf("--------------------------------------------------------");
	
/*					//while문을 list_len(list)만큼 반복할 때 유효한 코드  
					//fill code this part - end
					if(cnt==(list_len(list)))
					{
						break;
					}
*/
				}
				
				break;
				
			case 2:
				printf("which month ? : ");
				scanf("%i", &month);
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//file code here -- print scheduling info elements matching to the month
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)

					sched_getMonth(&month);				
/*					
					sched_getMonth(month)의 반환값이 상수일 때의 코드  
					
					//for(cnt=0; cnt<(sched_getMonth(month)); cnt++)
					//또는 while문 자체를 반복  
					//스케줄 리스트 순서  
					printf("%d. ", cnt+1);
					//스케줄 정보 (이름(유형)/월.일/장소) 
					sched_print(cnt);
					
					//while문을 sched_getMonth(month)만큼 반복할 때 유효한 코드  
					//fill code this part - end
					cnt++;
					if(cnt==(sched_getMonth(month)))
					{
						break;
					}
*/					
				}
				
				break;
				
			case 3:
				printf("which place ? : ");
				scanf("%s", &place);
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//file code here -- print scheduling info elements matching to the place
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					
					sched_getPlace(&place);
					
					
/*					
					sched_getPlace(place)의 반환값이 상수일 때의 코드 
					
					//for(cnt=0; cnt<(sched_getPlace(place)); cnt++)
					//또는 while문 자체를 반복  
					//스케줄 리스트 순서  
					printf("%d. ", cnt+1);
					//스케줄 정보 (이름(유형)/월.일/장소) 
					sched_print(cnt);
					
					//while문을 sched_getPlace(place)만큼 반복할 때 유효한 코드  
					//fill code this part - end
					cnt++;
					if(cnt==(sched_getPlace(place)))
					{
						break;
					}
*/
				}
				
				break;
				
			case 4:
				printf("which type ?\n");
				sched_printTypes();
				printf("your choice : ");
				scanf("%s", &typeName);

				if ((typeName == "drama")||(typeName == "movie")||(typeName == "advertisement")||(typeName == "entertainment")||(typeName == "meeting")||(typeName == "fitness")||(typeName == "privacy"))
				{
					ndPtr = list;
					while (list_isEndNode(ndPtr) == 0)
					{
						//file code here -- print scheduling info elements matching to the place
						ndPtr = list_getNextNd(ndPtr); //get the next node from the list
						schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)

						type = sched_convertType(typeName);	
						sched_getType(&type);
/*					
						sched_getType(type)의 반환값이 상수일 때의 코드 	
						
						//for(cnt=0; cnt<(sched_getType(type)); cnt++)
						//또는 while문 자체를 반복  
						//스케줄 리스트 순서  
						printf("%d. ", cnt+1);
						//스케줄 정보 (이름(유형)/월.일/장소) 
						sched_print(cnt);
					
						//while문을 sched_getType(type)만큼 반복할 때 유효한 코드 
						//fill code this part - end
						cnt++;
						if(cnt==(sched_getType(type)))
						{
							break;
						}
*/
					}
				}
				else
				{
					printf("wrong type name!\n");
				}
				break;
				
			case 5:
				printf("Bye!\n\n");
				exit_flag = 1;
				break;
				
			default:
				printf("wrong command! input again\n");
				break;
		}
		
		
	}
	
	return 0;
}
