#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "schedule.h"
#include "linkedList.h"

/* run this program using the console pauser or add your own getch, system("pause") or input loop */

int main(int argc, char *argv[]) {
	
	int exit_flag = 0;
	FILE *fp;	//파일포인터  
	
	char name[200];
	char place[100], typeName[100];	
	size_t size;					//사용자 정의 변수  
	int month;
	int day;
	int type;
	void *list;
	void *ndPtr;
	void *schedInfo;
	int option;
	int cnt;
	
	//1. FILE pointer open & error handling
	//1. 파일 포인터 열기 &  오류 처리  
	//fill code here ----
	fp = fopen("schedule.dat", "rb");
	if(fp == NULL)
	{
		printf("file path is wrong! %s\n", *fp);
		return -1;
	}
	
	//initializing the list
	//목록 초기화  
	printf("Reading the data files... \n");
	list = (void*)list_genList();
	
	
	
	
	//2. read from the file
	//2. 파일에서 읽어오기  
	while ( /* fill code here -- read from the file*/ )
	{	
		//fill code here -- generate genSchedInfo structure by genSchedInfo function
		//genSchedInfo 함수를 이용하여 genSchedInfo 구조체 생성하기  
		schedInfo = &sched_genSchedInfo;
		
		//put the scheduling info instance generated by genSchedInfo function
		//genSchedInfo 함수에 의해 생성된 스케줄링 정보 인스턴스 저장하기  
		list_addTail(schedInfo, list);	//50번째 줄의 schedInfo와 39번째 줄의 list 
	}
	
	
	//fill code here ---- close the file pointer
	//파일 포인터 닫기 
	fclose(fp); 
	
	printf("Read done! %i schedules are read\n", list_len(list));	//list의 길이  
	
	
	//program starts
	while(exit_flag == 0) 
	{
		//3. menu printing
		//메뉴 출력  
		//fill code here ---- 
		printf("1. print all the schedules\n");
		printf("2. search for schedules in the month\n");
		printf("3. search for schedules in the place\n");
		printf("4. search for specific type schedule\n");
		printf("5. exit\n\n");
		printf("  select an option : ");
		
/*		for(i=0; i<(list_len(list)); i++)
		{
			printf("%s %s %d %d %d\n", schedInfo.name, schedInfo.place, schedInfo.type, schedInfo.month, schedInfo.day);
		}
*/

		//4. get option from keyboard
		//fill code here ----
		//키보드로 옵션 받기  
		scanf("%d", &option);		
		
		switch(option)
		{
			case 1: //print all the schedules = 모든 스케줄 출력  
				printf("printing all the schedules in the scheduler.....\n\n\n");
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//file code here -- print count and each scheduling info element
					//카운트와 각 스케줄 정보 요소 출력  
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list = 리스트에서 다음 노드 얻기  
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info) = 

					
					//fill code this part - end
				}
				
				break;
				
			case 2:
				printf("which month ? : ");
				scanf("%i", &month);
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//file code here -- print scheduling info elements matching to the month
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					
					//fill code this part - end
				}
				
				break;
				
			case 3:
				printf("which place ? : ");
				scanf("%s", place);
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//file code here -- print scheduling info elements matching to the place
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					
					//fill code this part - end
				}
				
				break;
				
			case 4:
				printf("which type ?\n");
				sched_printTypes();
				printf("your choice : ");
				scanf("%s", typeName);
				
				if (/* fill code here -- convert the type and check if the type is valid */)
				{
					ndPtr = list;
					while (list_isEndNode(ndPtr) == 0)
					{
						//file code here -- print scheduling info elements matching to the place
						ndPtr = list_getNextNd(ndPtr); //get the next node from the list
						schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
						
						//fill code this part - end
					}
				}
				else
				{
					printf("wrong type name!\n");
				}
				break;
				
			case 5:
				printf("Bye!\n\n");
				exit_flag = 1;
				break;
				
			default:
				printf("wrong command! input again\n");
				break;
		}
		
		
	}
	
	return 0;
}
